_wandb:
  value:
    t: test
batch_size:
  value: 32
epochs:
  value: 10
lr:
  value: 0.001
model:
  value:
    name: ResNet18
    pretrained: true
optimizer:
  value: Adam
weight_decay:
  value: 0.0001
